package Enums;

public enum FilterArgNames {
    MINDEPTH, MAXDEPTH,
    NAME, PATH,
    ACCESS_TIME_OLDER, ACCESS_TIME_NEWER, ACCESS_TIME_EQUAL_MIN, ACCESS_TIME_EQUAL_DAY,
    MODIFICATION_TIME_OLDER, MODIFICATION_TIME_NEWER, MODIFICATION_TIME_EQUAL_MIN, MODIFICATION_TIME_EQUAL_DAY,
    NEWER_ACCESS_TIME, NEWER_MODIFICATION_TIME,
    TYPE, EMPTY, GROUP, USER,
    SIZE_BIGGER, SIZE_SMALLER, SIZE_B_EQUAL, SIZE_KB_EQUAL, SIZE_MB_EQUAL, SIZE_GB_EQUAL,
    OR, AND
}
